import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Button from "../components/Button";
import Footer from "../components/Footer"

export default function Home() {
  return (
    <div>
      <Head>
        <title>NEAR dev 101</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="bg-white min-h-screen pt-44 overflow-hidden">
          <div className="bg-white px-[23px] lg:px-0 relative pt-12 h-[600px] lg:h-[500px] w-full">
            <div className=" hero-background-color absolute lg:-top-[550px] -top-[520px] opacity-[0.4] left-0 lg:-left-48 h-[100%] w-[50%] z-50"></div>
            <div className="hero-background-color absolute lg:-top-[550px] -top-[520px] opacity-[0.4] right-0 lg:right-0 h-[100%] w-[40%] z-50"></div>
            <div className="bg-white px-[23px] lg:px-0 relative pt-12 h-[600px] lg:h-[500px] w-full">
              <div className="text-center lg:w-[910px] mx-auto">
                <h1 className="lg:text-[72px] lg:w-full w-[200px] mx-auto font-medium text-[36px] text-color">
                  Get <span className="hero-text">NEAR</span> Certified!
                </h1>
                <p className="pt-5 pb-24 lg:text-[22px] text-lg text-gray-500 leading-[28px]">
                  We, in NEAR Balkans, know how important it is to have regional
                  and local support. Now you can become NEAR certified in a
                  regional language of preference and connect with our team to
                  support your further growth within the NEAR ecosystem.
                </p>
                <div className=" flex items-center justify-center">
                  <img src="/assets/arrow.svg" alt="" />
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col items-center justify-center text-center  mt-16 text-dark-100 font-medium text-[32px] lg:text-5xl leading-7 lg:leading-[60px] tracking-[-0.02em]">
            <h1>
              Making your NEAR
              <br /> learning easy.
            </h1>
          </div>

          <div className="lg:mt-[182px] mt-16 gap-y-4 px-[22px] lg:px-0 lg:max-w-[940px] mx-auto flex lg:flex-row flex-col-reverse lg:justify-between items-center">
            <div className="text-center lg:text-left">
              <h1 className="text-gray-600 font-medium text-2xl text-center lg:text-left lg:text-4xl leading-[44px] tracking-[-0.02em]">
                Open NEAR wallet
              </h1>
              <p className="text-gray-400 font-normal text-base lg:text-lg lg:leading-6 pt-[6px]">
                Opening a NEAR wallet is the first step and <br /> essential
                part of joining the NEAR community
                <br /> as well as starting this course.
              </p>
              <Button></Button>
            </div>
            <div className="lg:w-[296px] lg:h-[296px] w-[180px] h-[180px]">
              <img src="/assets/nearp.png" />
            </div>
          </div>
          <div className="lg:mt-[177px] lg:px-0 lg:max-w-[940px] mx-auto mt-16 px-[22px] flex gap-x-[179px] lg:flex-row flex-col gap-y-4 items-center">
            <div className="z-50">
              <div className="z-10 relative lg:w-[296px] lg:h-[296px] w-[180px] h-[180px]">
                <img src="/assets/global.svg" />
              </div>
            </div>
            <div className="text-center lg:text-left">
              <div>
                <h1 className="text-dark-100 font-medium text-2xl lg:text-4xl leading-[44px] tracking-[-0.02em] relative">
                  Complete the course
                  <div className="absolute top-[0] -mt-[38%] -left-[24%] hidden lg:block">
                    <img src="/assets/zig.svg" />
                  </div>
                </h1>
                <p className="text-gray-500 text-lg leading-6 mt-6">
                  In three simple modules, learn:
                </p>
                <div>
                  <div className="flex gap-x-3 gap-y-[10px] lg:items-end items-center lg:flex-row flex-col mt-6">
                    <img
                      src="/assets/image (7).png"
                      alt=""
                      className="h-10 w-10"
                    />
                    <p className="text-gray-500 font-normal text-base lg:text-lg lg:leading-6 ">
                      Essential NEAR concepts
                    </p>
                  </div>
                  <div className="flex gap-x-3 gap-y-[10px] lg:items-end items-center lg:flex-row flex-col mt-6">
                    <img
                      src="/assets/image (6).png"
                      alt=""
                      className="h-10 w-10"
                    />
                    <p className="text-gray-500 font-normal text-base lg:text-lg lg:leading-6 ">
                      Essential NEAR concepts
                    </p>
                  </div>
                  <div className="flex gap-x-3 gap-y-[10px] lg:items-end items-center lg:flex-row flex-col mt-6">
                    <img
                      src="/assets/image (5).png"
                      alt=""
                      className="h-10 w-10"
                    />
                    <p className="text-gray-500 font-normal text-base lg:text-lg lg:leading-6 ">
                      Essential NEAR concepts
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="grid px-5 justify-items-center mt-16 lg:mt-[180px]">
            <div className="text-center mx-auto">
              <h1 className="text-dark-100 text-center font-medium text-2xl lg:text-4xl leading-[44px] tracking-[-0.02em] relative">
                Claim NEAR certificate
                <div className="hidden lg:block absolute top-0 -mt-[38%] left-[40%]">
                  <img src="/assets/zag.svg" alt="arrow" />
                </div>
              </h1>
              <p className="text-gray-500 font-normal text-lg leading-6 text-center">
                Upon course completion, receive the NEAR dev 101
                <br /> certificate as an NFT on your NEAR wallet.
              </p>
            </div>
            <div className="max-w-2xl py-24">
              <img src="/assets/certificate.png" alt="completion-certicate" />
            </div>
          </div>
          <div className="w-full bg-white">
            <div className="lg:px-[148px] flex lg:flex-row flex-col-reverse justify-between items-center mt-[168px]">
              <div className="relative text-center lg:text-left">
                <h1 className="text-dark-100 font-medium text-2xl lg:text-4xl leading-[44px] tracking-[-0.02em]">
                  NEAR Development 101
                </h1>
                <Button></Button>
                <div class="bottom-background w-[1067px] h-[240px] top-[5%] -left-[15%] absolute hidden lg:block"></div>
              </div>
              <div className="lg:w-[400px] lg:h-[400px] w-[180px] h-[180px]">
                <img src="/assets/near-logo.png" />
                <div class="above-background w-fit max-w-[1135px] h-[159px] absolute z-0 top-[80%] left-[20%] hidden lg:block"></div>
              </div>
            </div>
          </div>
        </div>
      </main>
<Footer/>
      
    </div>
  );
}
